server:
  port: 10002
database:
  type: "sqlite" # "sqlite" 或 "mysql"
  mysql:
    host: "192.168.192.36"
    port: 3306
    user: "byzhao"
    password: "zby123456"
    dbname: "byzhao"
  sqlite:
    file: "push.db"
apns:
  keyId: "LH4T9V5U4R"
  teamId: "5U8LBRXG3A"
  authKeyFile: "AuthKey_LH4T9V5U4R_5U8LBRXG3A.p8"